language: objective-c
sudo: required
dist: xenial
osx_image: xcode10.1
env:
    - SWIFT_VERSION=4.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - xcodebuild test -scheme CommandLine -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)

